version: 0.2

phases:
  install:
    commands:
      # Install dependencies
      - apt-get update
      - apt-get install -y build-essential libpq-dev libsqlite3-dev libxml2-dev libxslt1-dev
      - gem install bundler
      - bundle install --verbose
  pre_build:
    commands:
      - bundle exec rake db:create
      - bundle exec rake db:migrate
  build:
    commands:
      - bundle exec rake assets:precompile
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'public'

